env:
  browser: true
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  extraFileExtensions: ['.svelte']
plugins:
  - '@typescript-eslint'
  - 'svelte3'
  - 'unused-imports'
overrides: [{files: ['*.svelte'], processor: 'svelte3/svelte3'}]
rules: {
  no-unused-vars: off
  }
settings: {
  'svelte3/typescript': true
}